# Generated by Django 5.0.4 on 2024-05-06 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('income_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='income_models.basemodel')),
                ('book_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('is_active', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='school_library.author', verbose_name='Автор')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('income_models.basemodel',),
        ),
    ]
