# Generated by Django 5.0.4 on 2024-05-06 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='income_models.basemodel')),
                ('magazine_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('income_models.basemodel',),
        ),
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='income_models.basemodel')),
                ('newspaper_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('income_models.basemodel',),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('stoage_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('sum_cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Сумма')),
                ('operation_date', models.DateField(verbose_name='Дата операции')),
                ('operation_type', models.CharField(choices=[('Приход', 'Приход'), ('Расход', 'Расход')], max_length=255, verbose_name='Тип операции')),
                ('active', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storages', to='income_models.basemodel', verbose_name='Актив')),
            ],
        ),
    ]
